spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: from.email@gmail.com # логин от учётки Google
    password: "somepassword" # специальный пароль для приложения (см. Google Account)
    test-connection: true # проверка подключения при старте приложения
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender: # отправитель письма (его почта и имя)
      email: no-reply@example.com
      text: no-reply
